### ISSUE TITLE
join forces with jgrosso (from Axel) maybe

### ISSUE THREAD

**Issue by reuleaux** [raxod502/kalyn#24]
I have read your Kalyn blog https://intuitiveexplanations.com/tech/kalyn at the time with interest, but not in very much technical detail (I didn't have the time, and still don't have it - sorry).

But I am very much in favour of a more Haskell style lisp (and maybe some time this could take off?).
And to that end I had an eye on the other similar in spirit project: _Axel_ https://axellang.github.io/
(where I left a similar encouraging, but excusing myself, comment in the issue tracker some time ago:
https://github.com/axellang/axel/issues/77).

Now I am just thinking: maybe you two could join forces, and work together, on one codebase?
(I am not really in a position to judge: which one is better: Kalyn or Axel, and in wich sense  - but I assume, you guys could discuss this). - Have you contacted Joshua  https://github.com/jgrosso yet ?
Just an idea. Thanks.

**Comment by raxod502** [comment]
No, I don't think that's in the cards. This is because Kalyn is not intended to be a real general-purpose programming language, but rather an educational exercise in compiler design. I've seen Axel and it seems perfectly nice, but it probably wouldn't benefit from the rather simplistic and hacky code I've written for Kalyn.
